name: Continuous Integration
on:
  push:
  pull_request:
jobs:
  ci:
    name: CI for Preside Data API extension
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup flow variables
        run: |
          branch=${GITHUB_REF##*/}
          publish=false
          if [[ "{{ env.event.name }}" != "pull_request" ]] ; then
            if [[ $branch == release-* ]] || [[ $branch == v* ]] ; then
              publish=true
            fi
          fi
          echo "PUBLISH=$publish" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: pixl8/github-action-box-install@v2

      - name: Run tests
        uses: pixl8/github-action-box-test@v3
        with:
          boxjson_dir: /
          test_dir: /tests
          test_server_json: /server-samltests.json
          output_file: /tests/test-results.txt
          verbose: true

      - name: Upload Test Results Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/test-results.txt

      - name: Generate release version number
        if: "env.PUBLISH == 'true'"
        id: versiongen
        uses: pixl8/github-action-twgit-release-version-generator@v1

      - name: Inject version into box json
        if: "env.PUBLISH == 'true'"
        uses: dominicwatson/github-action-envsubst@v1
        with:
          files: box.json manifest.json
          patterns: $VERSION_NUMBER
        env:
          VERSION_NUMBER: ${{ steps.versiongen.outputs.semver_release_string }}

      - name: Zip project
        if: "env.PUBLISH == 'true'"
        run: zip -rq $ZIP_FILE * -x jmimemagic.log -x .* -x *.sh -x *.log -x tests/**\*
        shell: bash
        env:
          ZIP_FILE: ${{ steps.versiongen.outputs.semver_release_number }}.zip

      - name: Create Release
        if: "env.PUBLISH == 'true'"
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_PAT }}
          tag_name: ${{ steps.versiongen.outputs.semver_release_string }}
          name: Release ${{ steps.versiongen.outputs.semver_release_string }}
          target_commitish: ${{ github.sha }}
          prerelease: ${{ steps.versiongen.outputs.semver_release_is_snapshot }}
          files: ${{ steps.versiongen.outputs.semver_release_number }}.zip

      - name: Inject download location
        if: "env.PUBLISH == 'true'"
        uses: DominicWatson/github-action-envsubst@stable
        with:
          files: box.json
        env:
          DOWNLOAD_URL: ${{ fromJson(steps.create_release.outputs.assets)[0].browser_download_url }}

      - name: Publish to forgebox
        if: "env.PUBLISH == 'true'"
        uses: pixl8/github-action-box-publish@v3
        with:
          forgebox_user: ${{ secrets.FORGEBOX_USER }}
          forgebox_pass: ${{ secrets.FORGEBOX_PASS }}